### ISSUE TITLE
python@acgan.py@problem@Windows 10@Python 3.8.8@Anaconda

### ISSUE THREAD

**Issue by HyperGroups** [Jittor/gan-jittor#10]
PS C:\Users\HyperGroups\Documents\github\gan-jittor\models\acgan> python acgan.py
[i 1105 23:11:06.065000 84 compiler.py:944] Jittor(1.3.1.18) src: d:\programfiles\anaconda3\lib\site-packages\jittor
[i 1105 23:11:06.094000 84 compiler.py:945] cl at C:\Users\HyperGroups\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe(19.29.30133)
[i 1105 23:11:06.095000 84 compiler.py:946] cache_path: C:\Users\HyperGroups\.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6e\IntelRCoreTMi7x9d\default
[i 1105 23:11:06.099000 84 install_cuda.py:51] cuda_driver_version: [11, 4, 0]
[i 1105 23:11:06.125000 84 __init__.py:372] Found C:\Users\HyperGroups\.cache\jittor\jtcuda\cuda11.4_cudnn8_win\bin\nvcc.exe(11.4.100) at C:\Users\HyperGroups\.cache\jittor\jtcuda\cuda11.4_cudnn8_win\bin\nvcc.exe.
[i 1105 23:11:06.311000 84 __init__.py:372] Found gdb(8.1) at D:\ProgramFiles\mingw64\bin\gdb.EXE.
[i 1105 23:11:06.388000 84 __init__.py:372] Found addr2line(2.30) at D:\ProgramFiles\mingw64\bin\addr2line.EXE.
[i 1105 23:11:06.723000 84 compiler.py:997] cuda key:cu11.4.100_sm_86
[i 1105 23:11:06.726000 84 __init__.py:187] Total mem: 47.93GB, using 15 procs for compiling.
[i 1105 23:11:08.575000 84 jit_compiler.cc:27] Load cc_path: C:\Users\HyperGroups\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe
[i 1105 23:11:08.585000 84 init.cc:61] Found cuda archs: [86,]
[i 1105 23:11:08.928000 84 compile_extern.py:497] mpicc not found, distribution disabled.
[i 1105 23:11:10.902000 84 cuda_flags.cc:32] CUDA enabled.
Namespace(b1=0.5, b2=0.999, batch_size=64, channels=1, img_size=32, latent_dim=100, lr=0.0002, n_classes=10, n_cpu=8, n_epochs=200, sample_interval=400)
Conv shape [16,1,3,3,]
Conv shape [32,16,3,3,]
Conv shape [64,32,3,3,]
Conv shape [128,64,3,3,]

Compiling Operators(27/27) used: 16.1s eta:    0s

Compiling Operators(3/3) used: 6.55s eta:    0s
[e 1105 23:11:36.557000 08:C4 log.cc:526] cl : Command line warning D9025 : overriding '/EHa' with '/EHs'
_opkey0_broadcast_to_tx_int32__dim_2__bcast_2__jit_1__jit_cuda_1__index_t_int32___opkey1_b___hash_e3dacf6549a9b963_op.ccc1xx: fatal error C1083: Cannot open source file: 'c:\users\hypergroups\.cache\jittor\jt1.3.1\cl\py3.8.8\windows-10-10.x6e\intelrcoretmi7x9d\default\cu11.4.100_sm_86\jit\_opkey0_broadcast_to_tx_int32__dim_2__bcast_2__jit_1__jit_cuda_1__index_t_int32___opkey1_b___hash_e3dacf6549a9b963_op.cc': Permission denied
_opkey0_broadcast_to_tx_int32__dim_2__bcast_2__jit_1__jit_cuda_1__index_t_int32___opkey1_b___hash_e3dacf6549a9b963_op.cc
[e 1105 23:11:36.559000 08:C4 parallel_compiler.cc:270] [Error] source file location: C:\Users\HyperGroups\.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6e\IntelRCoreTMi7x9d\default\cu11.4.100_sm_86\jit\_opkey0_broadcast_to_Tx_int32__DIM_2__BCAST_2__JIT_1__JIT_cuda_1__index_t_int32___opkey1_b___hash_e3dacf6549a9b963_op.cc
[e 1105 23:11:36.559000 08:C4 parallel_compiler.cc:273] Compile fused operator(3/8) failed: [Op(000001712C20B360:0:0:1:i1:o1:s0,broadcast_to->000001712C20B400),Op(000001712C20BE00:1:1:2:i1:o1:s0,broadcast_to->000001712C20BEA0),Op(0000017129CA7B70:0:0:1:i1:o1:s0,index->000001712C20B540),Op(000001712BC6DA90:2:1:2:i2:o1:s0,binary.subtract->000001712C20BAE0),Op(0000017129CA7BF0:0:0:1:i2:o1:s0,binary.equal->000001712C20B5E0),Op(000001712BC6C110:1:1:2:i1:o1:s0,unary.exp->000001712C20BF40),Op(000001712BC6DB10:1:1:2:i2:o1:s0,binary.multiply->000001712C20D840),Op(000001712BC6DE10:1:1:2:i1:o1:s0,reduce.add->000001712C20C1C0),Op(000001712BC6D890:1:1:2:i1:o1:s0,reduce.add->000001712C20E9C0),]

Reason: [f 1105 23:11:36.558000 08:C4 log.cc:569] Check failed ret(2) == 0(0) Run cmd failed: "C:\Users\HyperGroups\.cache\jittor\jtcuda\cuda11.4_cudnn8_win\bin\nvcc.exe" "C:\Users\HyperGroups\.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6e\IntelRCoreTMi7x9d\default\cu11.4.100_sm_86\jit\_opkey0_broadcast_to_Tx_int32__DIM_2__BCAST_2__JIT_1__JIT_cuda_1__index_t_int32___opkey1_b___hash_e3dacf6549a9b963_op.cc"    -std=c++14 -Xcompiler -std:c++14      -shared  -L"d:\programfiles\anaconda3\libs" -lpython38  -Xcompiler -EHa -Xcompiler -MD   -I"C:\Users\HyperGroups\.cache\jittor\msvc\VC\include" -I"C:\Users\HyperGroups\.cache\jittor\msvc\win10_kits\include\ucrt" -I"C:\Users\HyperGroups\.cache\jittor\msvc\win10_kits\include\shared" -I"C:\Users\HyperGroups\.cache\jittor\msvc\win10_kits\include\um" -DNOMINMAX  -L"C:\Users\HyperGroups\.cache\jittor\msvc\VC\lib" -L"C:\Users\HyperGroups\.cache\jittor\msvc\win10_kits\lib\um\x64" -L"C:\Users\HyperGroups\.cache\jittor\msvc\win10_kits\lib\ucrt\x64"  -I"d:\programfiles\anaconda3\lib\site-packages\jittor\src" -I"d:\programfiles\anaconda3\include" -DHAS_CUDA -I"C:\Users\HyperGroups\.cache\jittor\jtcuda\cuda11.4_cudnn8_win\include" -I"d:\programfiles\anaconda3\lib\site-packages\jittor\extern\cuda\inc"  -lcudart -L"C:\Users\HyperGroups\.cache\jittor\jtcuda\cuda11.4_cudnn8_win\lib\x64" -L"C:\Users\HyperGroups\.cache\jittor\jtcuda\cuda11.4_cudnn8_win\bin"  -I"C:\Users\HyperGroups\.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6e\IntelRCoreTMi7x9d\default\cu11.4.100_sm_86" -L"C:\Users\HyperGroups\.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6e\IntelRCoreTMi7x9d\default\cu11.4.100_sm_86" -L"C:\Users\HyperGroups\.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6e\IntelRCoreTMi7x9d\default"  -l"jit_utils_core.cp38-win_amd64"  -l"jittor_core.cp38-win_amd64"  -x cu --cudart=shared -ccbin="C:\Users\HyperGroups\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe" --use_fast_math  -w  -I"d:\programfiles\anaconda3\lib\site-packages\jittor\extern/cuda/inc"  -arch=compute_86  -code=sm_86  -o "C:\Users\HyperGroups\.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6e\IntelRCoreTMi7x9d\default\cu11.4.100_sm_86\jit\_opkey0_broadcast_to_Tx_int32__DIM_2__BCAST_2__JIT_1__JIT_cuda_1__index_t_int32___opkey1_b___hash_e3dacf6549a9b963_op.dll" -Xlinker -EXPORT:"?jit_run@FusedOp@jittor@@QEAAXXZ"
[w 1105 23:11:42.218000 84 parallel_compiler.cc:101] Compile thread timeout, ignored.
Traceback (most recent call last):
  File "acgan.py", line 177, in <module>
    print(('[Epoch %d/%d] [Batch %d/%d] [D loss: %f, acc: %d%%] [G loss: %f]' % (epoch, opt.n_epochs, i, len(dataloader), d_loss.mean().data, (100 * d_acc), g_loss.mean().data)))
RuntimeError: Wrong inputs arguments, Please refer to examples(help(jt.data)).

Types of your inputs are:
 self   = Var,

The function declarations are:
 inline DataView data()

Failed reason:[f 1105 23:11:45.835000 84 parallel_compiler.cc:325] Error happend during compilation, see error above.

**Comment by HyperGroups** [comment]
有个小问题，jittor的许多仓库，开daili了有的下不了。
Solved.

**Comment by HyperGroups** [comment]
daili 问题

**Comment by zhouwy19** [comment]
Sorry.

I see "Permission not allowed" appears in your log.

Can you try this command "python3.7 -m jittor.test.test_cuda" and then provide a complete log report ?

Thank you.
