### ISSUE TITLE
example@esrgan.py@win10

### ISSUE THREAD

**Issue by HyperGroups** [Jittor/gan-jittor#11]
PS C:\Users\HyperGroups\Documents\github\gan-jittor\models\esrgan> python esrgan.py
[i 1105 23:26:43.515000 52 compiler.py:944] Jittor(1.3.1.18) src: d:\programfiles\anaconda3\lib\site-packages\jittor
[i 1105 23:26:43.555000 52 compiler.py:945] cl at C:\Users\HyperGroups\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe(19.29.30133)
[i 1105 23:26:43.556000 52 compiler.py:946] cache_path: C:\Users\HyperGroups\.cache\jittor\jt1.3.1\cl\py3.8.8\Windows-10-10.x6e\IntelRCoreTMi7x9d\default
[i 1105 23:26:43.560000 52 install_cuda.py:51] cuda_driver_version: [11, 4, 0]
[i 1105 23:26:43.591000 52 __init__.py:372] Found C:\Users\HyperGroups\.cache\jittor\jtcuda\cuda11.4_cudnn8_win\bin\nvcc.exe(11.4.100) at C:\Users\HyperGroups\.cache\jittor\jtcuda\cuda11.4_cudnn8_win\bin\nvcc.exe.
[i 1105 23:26:43.812000 52 __init__.py:372] Found gdb(8.1) at D:\ProgramFiles\mingw64\bin\gdb.EXE.
[i 1105 23:26:43.898000 52 __init__.py:372] Found addr2line(2.30) at D:\ProgramFiles\mingw64\bin\addr2line.EXE.
[i 1105 23:26:44.247000 52 compiler.py:997] cuda key:cu11.4.100_sm_86
[i 1105 23:26:46.055000 52 jit_compiler.cc:27] Load cc_path: C:\Users\HyperGroups\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe
[i 1105 23:26:46.055000 52 parallel_compiler.cc:25] Load use_parallel_op_compiler: 0
[i 1105 23:26:46.060000 52 init.cc:61] Found cuda archs: [86,]
[i 1105 23:26:46.159000 52 compile_extern.py:497] mpicc not found, distribution disabled.
[i 1105 23:26:49.237000 52 cuda_flags.cc:32] CUDA enabled.
Namespace(b1=0.9, b2=0.999, batch_size=4, channels=3, checkpoint_interval=5000, dataset_name='img_align_celeba', decay_epoch=100, epoch=0, hr_height=256, hr_width=256, lambda_adv=0.005, lambda_pixel=0.01, lr=0.0002, n_cpu=8, n_epochs=200, residual_blocks=23, sample_interval=100, warmup_batches=500)
Traceback (most recent call last):
  File "esrgan.py", line 101, in <module>
    for i, imgs in enumerate(dataloader):
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\jittor\dataset\dataset.py", line 496, in __iter__
    if self._disable_workers:
AttributeError: 'ImageDataset' object has no attribute '_disable_workers'

**Comment by zhouwy19** [comment]
Thank you for reminding! This is a bug. Now update this repository and it will work normally!
