### ISSUE TITLE
Segfault when train wgan-gp

### ISSUE THREAD

**Issue by yinghdb** [Jittor/gan-jittor#9]
Training with gradient penalty will cause segfault.
The training errors:

`
Caught segfault at address 0x60, thread_name: 'C0', flush log...
Segfault, exit
[e 1013 22:49:15.494524 68 parallel_compiler.cc:318] Segfault happen, main thread exit
`

I have tried the code in Ubuntu, on 1080 Ti and 3090.

**Comment by zhouwy19** [comment]
Sorry.

Can you try this command "use_parallel_op_compiler=0 python3.7 wgan_gp.py" and then provide a complete log report ?
